### ISSUE TITLE
Does not show the loading

### ISSUE THREAD

**Issue by fabian1122** [joaolfp/TMDB#1]
I am following your demo to understand how states and MVVMs work but I have a question, how can I make the loaded "loadingBehavior ()" work, I am struggling with this problem for several days. Please can you help me with that

Thank you.

**Comment by joaolfp** [comment]
Hi Fabian,

thank you very much for questioning, I really had a bug. I changed the implementation of ViewState to use the Observer pattern.

The ViewState class has a new method called fetchSource and now loading is working :)

```swift
self.viewState.fetchSource {
    self.service.getApiMovie(
         onSuccess: { (resultArray) in
              self.movieArray = MovieMapper(resultArray: resultArray).transform()
              self.viewState.success(data: self.movieArray)
     },
         onError: { (messageError) in
               self.viewState.error(error: messageError)
     })
}
```
Thank you very much for your contribution!!

**Comment by fabian1122** [comment]
Thanks, now it works perfect.
